"""Create/refresh the per-observation QA tracking issues on GitHub.

For each registered :class:`~data_qa.observations.Observation` this renders a filled
QA template (metadata + links to the data products + a QA checklist) and creates a
GitHub issue for it.  Idempotent: keyed on the issue title, so re-running updates the
existing issue body instead of duplicating.  Stdlib-only (urllib) so it runs in CI with
just ``GITHUB_TOKEN``.

Usage:
    python -m data_qa.make_issues --program 2221 1182 --target Brick
    python -m data_qa.make_issues --program 2221 1182 --dry-run
"""
from __future__ import annotations

import argparse
import json
import os
import sys
import urllib.error
import urllib.parse
import urllib.request

from .observations import Observation, registry

REPO = os.environ.get("QA_REPO", "JWST-GC/data-qa")
API = "https://api.github.com"

# Marker so we can recognize (and update) an auto-generated body without clobbering
# human discussion, which lives in the comments, not the body.
AUTOGEN_MARKER = "<!-- data-qa:autogen -->"


# --------------------------------------------------------------------------- body
def render_body(o: Observation) -> str:
    filt_rows = "\n".join(f"  - [ ] `{f}` — mosaic reviewed; astrometry + photometry OK"
                          for f in o.filters) or "  - (filters TBD)"
    visits = ", ".join(o.visits) or "—"
    notes = f"\n> **Notes:** {o.notes}\n" if o.notes else ""
    return f"""{AUTOGEN_MARKER}
**Observation `{o.obsid}`** — {o.target} / {o.instrument}

| field | value |
|-------|-------|
| Program | `{int(o.program)}` |
| Observation | `{o.obs}` (`{o.obsid}`) |
| Target | {o.target} |
| Instrument | {o.instrument} |
| Filters | {", ".join(f"`{f}`" for f in o.filters) or "—"} |
| Executions (visits) | {visits} |
| Epoch (DATE-OBS) | {o.epoch or "—"} |

### Data products
- MAST program: {o.mast_program_url}
- MAST search (this program): {o.mast_search_url}
- JWST-GC release: {o.release_url}
- On-disk mosaics: `{o.product_glob()}`
{notes}
### QA checklist
- [ ] Observation delivered / retrieved
- [ ] Per-filter mosaics (`i2d`) present and complete
{filt_rows}
- [ ] **Astrometry**: absolute frame tie (VIRAC2/Gaia) within survey noise
- [ ] **Astrometry**: no inter-module (NRCA/NRCB) offset (proper-motion grade)
- [ ] **Photometry**: zeropoints consistent across filters/modules
- [ ] Background / stripes / artifacts acceptable
- [ ] Catalog produced and vetted
- [ ] Known issues triaged (comment below)

---
*Auto-generated by `data_qa/make_issues.py` from the observation registry. Metadata is
kept in sync on re-runs; **discuss issues in the comments** (the body is overwritten).*
"""


def labels_for(o: Observation):
    return ["QA", o.instrument, f"program:{int(o.program)}", f"target:{o.target}"]


# --------------------------------------------------------------------------- GitHub API
def _req(method, url, token, data=None):
    body = json.dumps(data).encode() if data is not None else None
    req = urllib.request.Request(url, data=body, method=method)
    req.add_header("Authorization", f"token {token}")
    req.add_header("Accept", "application/vnd.github+json")
    req.add_header("User-Agent", "jwst-gc-data-qa")
    if body is not None:
        req.add_header("Content-Type", "application/json")
    try:
        with urllib.request.urlopen(req) as r:
            return r.status, json.loads(r.read().decode())
    except urllib.error.HTTPError as e:
        return e.code, json.loads(e.read().decode() or "{}")


def existing_issues(token, repo):
    """title -> issue dict, over all states (paginated)."""
    out, page = {}, 1
    while True:
        url = f"{API}/repos/{repo}/issues?state=all&per_page=100&page={page}"
        status, data = _req("GET", url, token)
        if status != 200 or not data:
            break
        for it in data:
            if "pull_request" in it:      # issues endpoint also returns PRs
                continue
            out[it["title"]] = it
        if len(data) < 100:
            break
        page += 1
    return out


def ensure_labels(token, repo, names):
    """Create any missing labels (best-effort; ignores 'already exists')."""
    palette = {"QA": "0e8a16", "NIRCam": "1d76db", "MIRI": "5319e7"}
    for n in names:
        color = palette.get(n, "ededed")
        _req("POST", f"{API}/repos/{repo}/labels", token,
             {"name": n, "color": color})


# --------------------------------------------------------------------------- main
def sync_observation(o, token, repo, existing, dry_run=False):
    title, body, labels = o.issue_title, render_body(o), labels_for(o)
    if title in existing:
        it = existing[title]
        num = it["number"]
        if dry_run:
            return f"UPDATE #{num}: {title}"
        _req("PATCH", f"{API}/repos/{repo}/issues/{num}", token,
             {"body": body, "labels": labels})
        return f"updated #{num}: {title}"
    if dry_run:
        return f"CREATE: {title}"
    ensure_labels(token, repo, labels)
    status, data = _req("POST", f"{API}/repos/{repo}/issues", token,
                        {"title": title, "body": body, "labels": labels})
    if status >= 300:
        return f"FAILED ({status}) {title}: {data.get('message')}"
    return f"created #{data['number']}: {title}"


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--program", nargs="*", help="program id(s) to include (default: all)")
    ap.add_argument("--target", help="restrict to a target name (e.g. Brick)")
    ap.add_argument("--repo", default=REPO, help=f"owner/name (default {REPO})")
    ap.add_argument("--dry-run", action="store_true", help="print actions, do not call GitHub")
    args = ap.parse_args(argv)

    obs = registry(programs=args.program, target=args.target)
    if not obs:
        print("no matching observations in the registry", file=sys.stderr)
        return 1
    token = os.environ.get("GITHUB_TOKEN") or os.environ.get("GH_TOKEN")
    if not token and not args.dry_run:
        print("GITHUB_TOKEN not set (use --dry-run to preview)", file=sys.stderr)
        return 2

    existing = existing_issues(token, args.repo) if token else {}
    for o in obs:
        print(sync_observation(o, token, args.repo, existing, dry_run=args.dry_run))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
